FROM node:20-alpine

WORKDIR /app

# Copiar manifiestos
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código (respetando .dockerignore)
COPY . .

# Exponer el puerto de Next.js
EXPOSE 3000

# El comando se anulará en docker-compose.
CMD ["npm", "run", "dev"]